//! IMPORTS
//* dependencies
import type { NextPage } from 'next';
import Head from 'next/head';

//* utils
import GoalContributionsChartWrapper from '@/components/Charts/GoalContributionsChartWrapper';

//* constants

//! JSX
const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GoalContributionsChartWrapper />
      </main>
    </div>
  );
};

export default HomePage;
